#include "EntityDef.h"

/* !!!! DO NOT MODIFY THIS FILE !!!! * This file was generated by EntGen.exe. Your changes will be overridden on the next build
 * If you want to change this file, change the relevant entity config file, or change the
 * EntityDef.hbs template file
 */
#include "SmallHealthPack.h"

using namespace ResWolf;

Entity* ResWolf::createEntity(int id, uint16_t x, uint16_t y, char* config)
{
    switch(id)
    {
    case SMALLHEALTHPACK:
    {
        return new SmallHealthPack(id, x, y, config);
    }
    }
}
