#pragma once

/* !!!! DO NOT MODIFY THIS FILE !!!! * This file was generated by EntGen.exe. Your changes will be overridden on the next build
 * If you want to change this file, change the relevant entity config file, or change the
 * EntityDef.hbs template file
 */
#include <stdint.h>

//#include "Entity.h"

namespace ResWolf
{
  //  Entity* createEntity(int id, uint16_t x,uint16_t y);
}
